### ISSUE TITLE
[QUESTION] Proyecto Localización Colombia

### ISSUE THREAD

**Issue by gorozcoh** [OCA/l10n-colombia#8]
Deseo contribuir al proyecto de Localización Colombia y tengo algunas inquietudes:

1. ¿De verdad no existe ni un solo módulo para la Localización Colombia? Es que me parece increíble!
2. ¿Además de las directrices generales publicadas en OCA guidelines hay algunas otras específicas a la localización?

Gracias por su amable respuesta.

Gustavo Orozco H.
App-247

**Comment by maovidal** [comment]
Hola Gustavo,
Yo tengo las mismas dudas. ¿Has podido resolver algo al respecto?

**Comment by gorozcoh** [comment]
Hola Mauricio. Negativo. Silencio absoluto...de hecho procedo a cerrar este issue de inmediato.
